//* https://api.themoviedb.org/3/movie/popular?api_key=52ef927bbeb21980cd91386a29403c78&language=ar

// (أول 20 فيلم) :بيانات أول صفحة

export const data = [
  {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg",
        genre_ids: [28, 878, 27],
        id: 615656,
        original_language: "en",
        original_title: "Meg 2: The Trench",
        overview:
          "في الجزء الثاني من الفيلم يستمر تتبع قصة جوناس حيث يقرر دراسة ميجالودون بعد اكتشافه أنه ما زال موجود، لكن المفاجأة التي لم يتوقعها جوناس هي مواجهة ديناصور غريب يعيش في الماء.",
        popularity: 6913.755,
        poster_path: "/uzqfE6NIkQHxv28HipFgiBQ4M3K.jpg",
        release_date: "2023-08-02",
        title: "القرش 2 : الخندق",
        video: false,
        vote_average: 7,
        vote_count: 1174,
      },
      {
        adult: false,
        backdrop_path: "/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg",
        genre_ids: [12, 28, 14],
        id: 335977,
        original_language: "en",
        original_title: "Indiana Jones and the Dial of Destiny",
        overview:
          "تدور احداث الفيلم حول إندي يجد نفسه في عصر جديد ، يقترب من التقاعد ، ويصارع من أجل الاندماج في عالم يبدو أنه تجاوزه. ولكن مع عودة مخالب شر مألوف للغاية في شكل منافس قديم ، يجب على اندي ارتداء قبعته والتقاط سوطه مرة أخرى للتأكد من عدم وقوع قطعة أثرية قديمة وقوية في الأيدي الخطأ.",
        popularity: 1820.987,
        poster_path: "/ihCGDoHik5dAaF2ho8wM8BBzZcl.jpg",
        release_date: "2023-06-28",
        title: "إنديانا جونز ونداء القدر",
        video: false,
        vote_average: 6.7,
        vote_count: 1172,
      },
      {
        adult: false,
        backdrop_path: "/jZIYaISP3GBSrVOPfrp98AMa8Ng.jpg",
        genre_ids: [16, 35, 10751, 14, 10749],
        id: 976573,
        original_language: "en",
        original_title: "Elemental",
        overview:
          "الأضداد تتفاعل.  في مدينة يعيش فيها سكان النار والماء والأرض والهواء معا ، ستكتشف شابة نارية ورجل يسير مع التدفق شيئا أساسيا: مقدار القواسم المشتركة بينهما.",
        popularity: 1782.085,
        poster_path: "/rvSzdzwfRjAeESh1BPIxjf4eklN.jpg",
        release_date: "2023-06-14",
        title: "مدينة العناصر",
        video: false,
        vote_average: 7.8,
        vote_count: 1648,
      },
      {
        adult: false,
        backdrop_path: "/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
        genre_ids: [35, 12, 14],
        id: 346698,
        original_language: "en",
        original_title: "Barbie",
        overview:
          "تعيش دمية في مدينة باربيلاند تُدعى باربي، وحينما تُطرد من المدينة بسبب عدم كونها مثالية، تنطلق باربي في مغامرة بالعالم الحقيقي على أمل إثبات جدارتها والعودة إلى وطنها.",
        popularity: 1255.043,
        poster_path: "/e8Lng7AmGnCYLq7XPQnI9prRF3S.jpg",
        release_date: "2023-07-19",
        title: "باربي",
        video: false,
        vote_average: 7.4,
        vote_count: 3572,
      },
      {
        adult: false,
        backdrop_path: "/xVMtv55caCEvBaV83DofmuZybmI.jpg",
        genre_ids: [53, 28],
        id: 724209,
        original_language: "en",
        original_title: "Heart of Stone",
        overview:
          "تسعى عميلة استخبارات تعمل لصالح منظمة عالمية سرية لحفظ السلام التصدي لمخترق إلكتروني يسعى لسرقة سلاح بالغ الخطورة.",
        popularity: 1124.013,
        poster_path: "/nCDh2iKI7HlrrNnKcfKuHyDbwbX.jpg",
        release_date: "2023-08-09",
        title: "قلب من حجر",
        video: false,
        vote_average: 6.9,
        vote_count: 921,
      },
      {
        adult: false,
        backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
        genre_ids: [16, 28, 12],
        id: 569094,
        original_language: "en",
        original_title: "Spider-Man: Across the Spider-Verse",
        overview:
          "بعد مرور فترة طويلة، يتلقى مايلز موراليس زيارة جديدة من جوين ستيسي، ومعًا ينطلق الثنائي في مغامرة جديدة مليئة بالمخاطر والأعداء عبر عالم العنكبوت.",
        popularity: 1067.957,
        poster_path: "/xmZSu0hdbuwb4mJIrocpKfnVjbZ.jpg",
        release_date: "2023-05-31",
        title: "سبايدر مان: عبر السبايدر-فيرس",
        video: false,
        vote_average: 8.5,
        vote_count: 3940,
      },
      {
        adult: false,
        backdrop_path: "/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
        genre_ids: [28, 12, 878],
        id: 667538,
        original_language: "en",
        original_title: "Transformers: Rise of the Beasts",
        overview:
          "تدور احداث الفيلم في إطار من الحركة والخيال العلمي، تظهر مجموعة من الحيوانات الآلية، مما يطلق العنان لحربا كبرى يشارك بها كافة المتحولون.",
        popularity: 989.275,
        poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
        release_date: "2023-06-06",
        title: "المتحولون: صعود الوحوش",
        video: false,
        vote_average: 7.5,
        vote_count: 3032,
      },
      {
        adult: false,
        backdrop_path: "/yF1eOkaYvwiORauRCPWznV9xVvi.jpg",
        genre_ids: [28, 12, 878],
        id: 298618,
        original_language: "en",
        original_title: "The Flash",
        overview:
          "يسافر الفلاش عبر الزمن لمنع مقتل والدته ، وهو عمل يعطل الوقت بشكل كبير.",
        popularity: 866.741,
        poster_path: "/abT8jngvBDk31BsVgMMNrP4OTIY.jpg",
        release_date: "2023-06-13",
        title: "The Flash",
        video: false,
        vote_average: 6.9,
        vote_count: 2645,
      },
      {
        adult: false,
        backdrop_path: "/fQvHTPken2biD5cA6jR0M2SE6Qg.jpg",
        genre_ids: [27, 14],
        id: 635910,
        original_language: "en",
        original_title: "The Last Voyage of the Demeter",
        overview:
          "السفينة التجارية ديميتر مستأجرة لحمل خمسين صندوقا خشبيا لا يحمل علامات من كارباثيا إلى لندن ، فقط ليجد طاقمها المنكوب أنفسهم مطاردين كل ليلة من خلال وجود غامض على متنها.",
        popularity: 829.595,
        poster_path: "/nrtbv6Cew7qC7k9GsYSf5uSmuKh.jpg",
        release_date: "2023-08-09",
        title: "The Last Voyage of the Demeter",
        video: false,
        vote_average: 7.4,
        vote_count: 246,
      },
      {
        adult: false,
        backdrop_path: "/waBWlJlMpyFb7STkFHfFvJKgwww.jpg",
        genre_ids: [28, 18],
        id: 678512,
        original_language: "en",
        original_title: "Sound of Freedom",
        overview:
          "يروي الفيلم قصة تيم بالارد، وهو عميل سابق، الذي استقال من وظيفته كعميل خاص في تحقيقات الأمن الداخلي (HSI) لإنقاذ الأطفال من الكارتل وتجار البشر.",
        popularity: 825.798,
        poster_path: "/kSf9svfL2WrKeuK8W08xeR5lTn8.jpg",
        release_date: "2023-07-03",
        title: "Sound of Freedom",
        video: false,
        vote_average: 8.2,
        vote_count: 387,
      },
      {
        adult: false,
        backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
        genre_ids: [28, 80, 53],
        id: 385687,
        original_language: "en",
        original_title: "Fast X",
        overview:
          "تدور احداث الفيلم حيث ينطلق (دانتي) - ابن زعيم الجريمة (هيرنان رييس) - الذي قُتل قبل عشر سنوات للانتقام من البطل (دوم توريتو) وعائلته وشركائه بعد التسبب في مقتل والده وسرقة أمواله.",
        popularity: 787.155,
        poster_path: "/mgBcSHJt8fcRfXn8LcWusrCt0Kw.jpg",
        release_date: "2023-05-17",
        title: "السريع 10",
        video: false,
        vote_average: 7.3,
        vote_count: 3537,
      },
      {
        adult: false,
        backdrop_path: "/rRcNmiH55Tz0ugUsDUGmj8Bsa4V.jpg",
        genre_ids: [35, 10749],
        id: 884605,
        original_language: "en",
        original_title: "No Hard Feelings",
        overview:
          "تصبح مادي على وشك فقدان المنزل الذي تربت داخل جدرانه، فتقرر المشاركة في خطة لمساعدة عائلة ثرية ومواعدة ابنهم الانطوائي بيرسي والبالغ من العمر 19 عامًا، ولكن سرعان ما تكتشف مادي أن مهمتها ليست سهلة.",
        popularity: 638.767,
        poster_path: "/pGt2INo9GH9camSSYROC5OKHBwF.jpg",
        release_date: "2023-06-15",
        title: "لا مشاعر قاسية",
        video: false,
        vote_average: 7.2,
        vote_count: 1041,
      },
      {
        adult: false,
        backdrop_path: "/8FQeHmusSN2hk3bICf16x5GFQvT.jpg",
        genre_ids: [12, 10751, 14, 10749],
        id: 447277,
        original_language: "en",
        original_title: "The Little Mermaid",
        overview:
          "أصغر بنات الملك تريتون ، والأكثر تحديا ، يتوق أرييل لمعرفة المزيد عن العالم وراء البحر ، وأثناء زيارته للسطح ، يقع في حب الأمير إريك المحطم. مع منع حوريات البحر من التفاعل مع البشر ، تعقد آرييل صفقة مع ساحرة البحر الشريرة ، أورسولا ، مما يمنحها فرصة لتجربة الحياة على الأرض ، لكنه في النهاية يعرض حياتها - وتاج والدها - للخطر.",
        popularity: 584.681,
        poster_path: "/hl5sr2o0CJxXn8sKSNXpQ5B3b2D.jpg",
        release_date: "2023-05-18",
        title: "The Little Mermaid",
        video: false,
        vote_average: 6.6,
        vote_count: 1747,
      },
      {
        adult: false,
        backdrop_path: "/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
        genre_ids: [18, 36],
        id: 872585,
        original_language: "en",
        original_title: "Oppenheimer",
        overview:
          "فلم يحكي السيرة الذاتية وقصة العالم الأمريكي روبرت أوبنهايمر ودوره في تطوير القنبلة الذرية، وكيف غير مشروع مانهاتن من كل شيء في العالم.",
        popularity: 578.455,
        poster_path: "/fj4Sw2PihpjJkkeyhAWV5x933no.jpg",
        release_date: "2023-07-19",
        title: "أوبنهايمر",
        video: false,
        vote_average: 8.3,
        vote_count: 2972,
      },
      {
        adult: false,
        backdrop_path: "/bz66a19bR6BKsbY8gSZCM4etJiK.jpg",
        genre_ids: [28, 9648, 53, 27],
        id: 1006462,
        original_language: "en",
        original_title: "The Flood",
        overview:
          "خلال عاصفة قوية وطوفان مروع، يصبح مجموعة من السجناء في خطر حينما يتعرضوا لهجوما من التماسيح الجائعة.",
        popularity: 547.522,
        poster_path: "/tbyhg1DxQkkKUmQ60x7dqGxPvt1.jpg",
        release_date: "2023-07-14",
        title: "The Flood",
        video: false,
        vote_average: 6.9,
        vote_count: 179,
      },
      {
        adult: false,
        backdrop_path: "/vcQQx1z5iUbqZ3uJXvfCCMN3HPb.jpg",
        genre_ids: [28, 35],
        id: 869855,
        original_language: "nl",
        original_title: "H4Z4RD",
        overview: "",
        popularity: 529.249,
        poster_path: "/gUjmpgsG7fxPWejTmPMDLxFT7Yr.jpg",
        release_date: "2022-07-20",
        title: "H4Z4RD",
        video: false,
        vote_average: 6,
        vote_count: 6,
      },
      {
        adult: false,
        backdrop_path: "/4Yon9Qmg3U4onL0OywXAHSkFTUG.jpg",
        genre_ids: [28, 18],
        id: 1163045,
        original_language: "yo",
        original_title: "Jagun Jagun: The Warrior",
        overview: "",
        popularity: 528.859,
        poster_path: "/jTLgX0DgJS8vMCroe4NGgUD04jd.jpg",
        release_date: "2023-08-10",
        title: "Jagun Jagun: The Warrior",
        video: false,
        vote_average: 6.9,
        vote_count: 33,
      },
      {
        adult: false,
        backdrop_path: "/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
        genre_ids: [878, 12, 28],
        id: 447365,
        original_language: "en",
        original_title: "Guardians of the Galaxy Vol. 3",
        overview:
          "لا يزال بيتر كويل يعاني من خسارة جامورا، ويحشد فريقه للدفاع عن الكون وعلى واحد من أعضاء فريقه - وهي مهمة قد تعني نهاية الحراس إذا لم تنجح.",
        popularity: 517.46,
        poster_path: "/m4wEKqmhkXaFAOpEwYJX6u6AYcZ.jpg",
        release_date: "2023-05-03",
        title: "حرّاس المجرّة المجلد 3",
        video: false,
        vote_average: 8,
        vote_count: 4603,
      },
      {
        adult: false,
        backdrop_path: "/hPcP1kv6vrkRmQO3YgV1H97FE5Q.jpg",
        genre_ids: [27, 9648, 53],
        id: 614479,
        original_language: "en",
        original_title: "Insidious: The Red Door",
        overview:
          "يتجه جوش لامبرت إلي الشرق لإيصال ابنه دالتون للمدرسة. سرعان ما يتحول حلم دالتون للدراسة الجامعية إلي كابوس، عندما تعود الشياطين المحبوسة من ماضيه فجأة لتطاردهم هما الاثنين.",
        popularity: 495.549,
        poster_path: "/d07phJqCx6z5wILDYqkyraorDPi.jpg",
        release_date: "2023-07-05",
        title: "Insidious: The Red Door",
        video: false,
        vote_average: 6.9,
        vote_count: 1007,
      },
      {
        adult: false,
        backdrop_path: "/2D6ksPSChcRcZuvavrae9g4b8oh.jpg",
        genre_ids: [16, 14, 12, 10751, 35],
        id: 832502,
        original_language: "en",
        original_title: "The Monkey King",
        overview:
          "استنادَا إلى قصة أسطورية صينية شهيرة، يدور العمل حول قرد يمتلك عصا سحرية، ويخوض العديد من المعارك ضد الشياطين والتنانين والملوك في سبيل تحقيق العدالة.",
        popularity: 494.903,
        poster_path: "/i6ye8ueFhVE5pXatgyRrZ83LBD8.jpg",
        release_date: "2023-08-11",
        title: "The Monkey King",
        video: false,
        vote_average: 7,
        vote_count: 108,
      },
    ],
    total_pages: 39834,
    total_results: 796673,
  },
];
