export const items = [
  {
    id: Math.random(),
    title: "وجبة إفطار",
    description: "وصف وجبة الإفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وصف وجبة الغداء",
    price: "60 جنيه",
    category: "غداء",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبة غداء 2",
    description: "وصف وجبة الغداء 2",
    price: "40 جنيه",
    category: "غداء",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "وجبة إفطار",
    description: "وصف وجبة الإفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وصف وجبة العشاء",
    price: "90 جنيه",
    category: "عشاء",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء 2",
    description: "وصف وجبة العشاء",
    price: "80 جنيه",
    category: "عشاء",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "وجبة غداء ممتاز",
    description: "وصف وجبة الغداء ممتاز",
    price: "30 جنيه",
    category: "غداء",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء درجة أولى",
    description: "وصف وجبة العشاء الدرجة الأولى",
    price: "50 جنيه",
    category: "عشاء",
    imgUrl: "2.png",
  },
  {
    id: Math.random(),
    title: "وجبة إفطار",
    description: "وصف وجبة الإفطار",
    price: "50 جنيه",
    category: "فطار",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبة سناك",
    description: "وصف وجبة السناك",
    price: "50 جنيه",
    category: "سناك",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "وجبة سناك",
    description: "وصف وجبة السناك",
    price: "50 جنيه",
    category: "سناك",
    imgUrl: "3.png",
  },
];
